window.document.writeln("<table width=\"120\" border=\"0\" cellpadding=\"2\" cellspacing=\"0\" class=\"stdTableAsGroupBox\">");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"><a href=\"advanced_collection1.html\" class=\"navlink\">Collections</a></td></tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"><a href=\"advanced_streams.html\" class=\"navlink\">Streams</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"advanced_readers.html\" class=\"navlink\">Readers &amp; Writers</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"advanced_serializable.html\" class=\"navlink\">Serialization</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"advanced_streamtokenizer.html\" class=\"navlink\">Other IO classes</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"awt_event.html\" class=\"navlink\">Events</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"awt_eventhandlers.html\" class=\"navlink\">Event Handling</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"awt_eventnew.html\" class=\"navlink\">EventListeners</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"awt_font.html\" class=\"navlink\">Font</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"swing.html\" class=\"navlink\">Swing</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"swing_jcomponent.html\" class=\"navlink\">Swing Components</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"contents.html#advanced\" class=\"navlink\">&lt; Contents</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"advanced_intro.html\" class=\"navlink\">&nbsp;Advanced &gt;</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> </td> </tr>");
window.document.writeln("</table>");
window.document.close();
