window.document.writeln("<table width=\"120\" border=\"0\" cellpadding=\"2\" cellspacing=\"0\" class=\"stdTableAsGroupBox\">");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"><a href=\"basics_intro.html\" class=\"navlink\">Introducing Java</a></td></tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"><a href=\"basics_objects.html\" class=\"navlink\">What is an Object?</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_class.html\" class=\"navlink\">The class statement</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_inheritance.html\" class=\"navlink\">Object Inheritance</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_package.html\" class=\"navlink\">Packaging classes</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_encapsulation.html\" class=\"navlink\">Object Encapsulation</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_methods.html\" class=\"navlink\">Methods in Objects</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_variables.html\" class=\"navlink\">Variables in Objects</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_constructors.html\" class=\"navlink\">Constructing Objects</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_polymorphism.html\" class=\"navlink\">Object Polymorphism</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_interface.html\" class=\"navlink\">Object Interfaces</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_example.html\" class=\"navlink\">Example</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_reference.html\" class=\"navlink\">Referencing Objects</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"basics_summary.html\" class=\"navlink\">Summary</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"contents.html#basics\" class=\"navlink\">&lt; Contents</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> <a href=\"programming_intro.html\" class=\"navlink\">&nbsp;Programming &gt;</a></td> </tr>");
window.document.writeln("<tr><td bgcolor=\"#CCCCCC\"> </td> </tr>");
window.document.writeln("</table>");
window.document.close();
